---
- hosts: all
  become: true
  tasks:
    - name: Configurando requisitos do network plugin
      ansible.builtin.script:
        cmd: provision.sh

    - name: instalando pacotes necessrios
      ansible.builtin.apt:
        name: "{{ pacotes }}"
        state: present
        update_cache: yes
      vars:
        pacotes:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common


    
    - name: criando diretorio para chave gpg
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: adicionado cheve do docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg 
        dest: /etc/apt/keyrings/docker.asc
        mode: 0754

    - name: adicionando repostorio
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu  {{ansible_distribution_release}} stable"
        filename: docker

    - name: instalando pacotes
      ansible.builtin.apt:
        name: "{{ pacotes }}"
        state: present
        update_cache: yes
      vars:
        pacotes:
        - containerd.io

    - name: criando diretorio do cni
      ansible.builtin.file:
        path: /opt/cni/bin
        state: directory
        mode: 0755
    
    - name: instalndo plugi cni do containerd
      ansible.builtin.unarchive:
        src: https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-amd64-v1.3.0.tgz
        dest: /opt/cni/bin 
        remote_src: yes

    - name: configurando o arquivo config.toml do containerd
      ansible.builtin.script:
        cmd: config.sh


    - name: adcionando chave gpg
      # ansible.builtin.get_url:
      #   url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
      #   dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  
      ansible.builtin.shell:
        cmd: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
   
        
    # - name: adicionado repostorio do kubernetes
    #   ansible.builtin.apt_repository:
    #     repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    #     filename: k8

    - name: adicionado repo do kubernetes
      ansible.builtin.shell:
        cmd: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg]" https://apt.kubernetes.io/ kubernetes-xenial main | sudo tee /etc/apt/sources.list.d/kubernetes.list

    
    # - name: instalando os binarios do kubernetes
    #   ansible.builtin.apt:
    #     name: "{{ binarios }}"
    #     state: present
    #     update_cache: yes
    #   vars:
    #     binarios:
    #     - kubelet 
    #     - kubeadm 
    #     - kubectl






...
  
