# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
    'master'  => {'memory' =>  '3096', 'cpu' => 2, 'image' => 'ubuntu/focal64', 'ip' => '50'},
    'node1'  => {'memory' => '3096', 'cpu' => 2, 'image' =>  'ubuntu/focal64', 'ip' => '60'},
}

Vagrant.configure("2") do |config|
machines.each do |name,conf|
    config.vm.define name do | machine|
        machine.vm.box = conf['image']
        machine.vm.network "public_network", bridge: "Intel Corporation Wireless 7260 (rev bb)", ip: "192.168.15.#{conf['ip']}"
        #machine.vm.network "forwarded_port", guest: 6443, host: 6443,
         #   auto_correct: true
        machine.vm.provision "ansible" do | ansible|
            ansible.playbook = "install.yml"
        machine.vm.provider "virtualbox" do |vb|
        vb.memory = conf ['memory']
        vb.cpus = conf ['cpu']
              end
          end 
      end
  end
end