
apiVersion: v1
kind: Pod

metadata:
  name: redis-pod
  labels:
    apps: backend

spec:
  containers:
    - name: redis-pod
      image: redis
      volumeMounts:
      - mountPath: /mnt/data
        name: host-path
  volumes: 
    - name: "host-path"
      hostPath:
        path: /my-data
        type: Directory