apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: worker
  name: vote
  Namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: dockersamples/exemplevotingapp_worker
          name: worker
