image:
  repository: velero/velero
  tag: v1.13.0
  pullPolicy: IfNotPresent
  imagePullSecrets: []
  resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi
initContainers:
   - name: velero-plugin-for-aws
     image: velero/velero-plugin-for-aws:v1.9.0
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - mountPath: /target
         name: plugins
configuration:
  backupStorageLocation:
  - name: eks
    provider: aws
    bucket: dev-velero
    caCert:
    prefix:
    default: "true"
    validationFrequency:
    accessMode: ReadWrite
    credential:
      name:
      key:
  volumeSnapshotLocation:
  - name: eks
    provider: aws
    credential:
      name:
      key:
    config: {}

  defaultBackupStorageLocation: eks

deployNodeAgent: true
nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  priorityClassName: ""
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi