image:
  repository: velero/velero
  tag: v1.13.0
  pullPolicy: IfNotPresent
  resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi
initContainers:
   - name: velero-plugin-for-aws
     image: velero/velero-plugin-for-aws:v1.9.0
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - mountPath: /target
         name: plugins
configuration:
  backupStorageLocation:
  - name: ${backupStorageLocation_name}
    provider: aws
    bucket: ${backupStorageLocation_bucket}
    default: "true"
  volumeSnapshotLocation:
  - name: ${backupStorageLocation_name}
    provider: aws
  defaultBackupStorageLocation: ${backupStorageLocation_name}
deployNodeAgent: true
nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi